name: Automatic approval on pull-requests of given user

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'pamparamp'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approval successful"

